[project]
name = "serviceme-babeldoc"
version = "0.0.1"
description = "Yet Another Document Translator"
license = "AGPL-3.0"
readme = "README.md"
requires-python = ">=3.11,<3.12"
authors = []
maintainers = []
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
keywords = ["PDF"]
dependencies = [
    "bitstring>=4.3.0",
    "configargparse>=1.7",
    "httpx[socks]>=0.27.0",
    "huggingface-hub>=0.27.0",
    "numpy>=2.0.2",
    "onnx>=1.18.0",
    "onnxruntime>=1.16.1",
    "openai>=1.59.3",
    "orjson>=3.10.14",
    "charset-normalizer>=2.0.0",
    "cryptography>=36.0.0",
    "peewee>=3.17.8",
    "psutil>=7.0.0",
    "pymupdf>=1.25.1,<1.25.3",
    "rich>=13.9.4",
    "toml>=0.10.2",
    "tqdm>=4.67.1",
    "xsdata[cli,lxml,soap]>=24.12",
    "msgpack>=1.1.0",
    "pydantic>=2.10.6",
    "tenacity>=9.0.0",
    "scikit-image>=0.25.2",
    "freetype-py>=2.5.1",
    "tiktoken>=0.9.0",
    "python-levenshtein>=0.27.1",
    "opencv-python-headless>=4.10.0.84",
    "rapidocr-onnxruntime>=1.4.4",
    "pyzstd>=0.17.0",
    "hyperscan>=0.7.13",
    "rtree>=1.4.0",
    "chardet>=5.2.0",
    "scipy>=1.15.3",
    "uharfbuzz>=0.50.2",
    "scikit-learn>=1.7.1",
    "requests",
    "ollama",
    "xinference-client",
    "deepl",
    "azure-ai-translation-text<=1.0.1",
    "gradio<5.36",
    "tencentcloud-sdk-python-tmt",
    "gradio-pdf>=0.0.21",
    "fontTools",
    "pydantic-settings>=2.8.1",
    "sse-starlette>=2.3.3",
    "fastapi>=0.115.12",
    "uvicorn>=0.34.2",
    "legacy-cgi; python_version >= '3.13'",
    "gradio-i18n>=0.3.1",
    "pyyaml>=6.0.2",
    "sqlmodel==0.0.14",
    "loguru==0.7.2",
    "psycopg2-binary==2.9.9",
    "celery==5.4.0",
    "redis==4.6.0"
]

[project.optional-dependencies]
directml = ["onnxruntime-directml>=1.16.1"]
cuda = ["onnxruntime-gpu>=1.16.1"]
memray = ["memray>=1.17.1"]

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = {find = {}}